#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

usage() {
  cat <<'EOF'
NiuOne one-click local runner

Usage:
  ./run.sh [options]

Options:
  --no-browser     Do not open the browser automatically
  --skip-install   Skip dependency installation
  --port VALUE     Save the dashboard port to dashboard.env before starting
  --service        Install and start native long-running services
  -h, --help       Show this help

Environment:
  NIUONE_LOCAL_DATA_DIR  Private runtime directory, default: .local-data
  DASHBOARD_HOST         Dashboard host, default: 127.0.0.1
  DASHBOARD_PORT         Dashboard port, default: 8787
EOF
}

normalize_port_arg() {
  local value="$1"
  if [[ ! "$value" =~ ^[0-9]+$ ]]; then
    echo "--port must be an integer between 1 and 65535" >&2
    return 1
  fi
  local port_num=$((10#$value))
  if (( port_num < 1 || port_num > 65535 )); then
    echo "--port must be an integer between 1 and 65535" >&2
    return 1
  fi
  printf '%s\n' "$port_num"
}

OPEN_BROWSER="${NIUONE_OPEN_BROWSER:-1}"
INSTALL_DEPS="${NIUONE_INSTALL_DEPS:-1}"
SERVICE_MODE=0
PORT_ARG=""
PORT_ARG_SET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-browser)
      OPEN_BROWSER=0
      ;;
    --skip-install)
      INSTALL_DEPS=0
      ;;
    --service)
      SERVICE_MODE=1
      ;;
    --port)
      if [[ $# -lt 2 ]]; then
        echo "--port requires a value" >&2
        usage >&2
        exit 2
      fi
      if ! PORT_ARG="$(normalize_port_arg "$2")"; then
        usage >&2
        exit 2
      fi
      PORT_ARG_SET=1
      shift
      ;;
    --port=*)
      if ! PORT_ARG="$(normalize_port_arg "${1#*=}")"; then
        usage >&2
        exit 2
      fi
      PORT_ARG_SET=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

LOCAL_DATA_DIR="${NIUONE_LOCAL_DATA_DIR:-$ROOT/.local-data}"
VENV_DIR="${NIUONE_VENV_DIR:-$LOCAL_DATA_DIR/.venv}"
ENV_FILE="${DASHBOARD_ENV_FILE:-$LOCAL_DATA_DIR/dashboard.env}"

write_env_value() {
  printf '%s=%q\n' "$1" "$2"
}

save_env_value() {
  local name="$1"
  local value="$2"
  local tmp line existing found
  mkdir -p "$(dirname "$ENV_FILE")"
  tmp="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
  chmod 600 "$tmp" 2>/dev/null || true
  line="$(write_env_value "$name" "$value")"
  found=0

  if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r existing || [[ -n "$existing" ]]; do
      if [[ "$existing" == "$name="* ]]; then
        if [[ "$found" == "0" ]]; then
          printf '%s\n' "$line" >> "$tmp"
          found=1
        fi
      else
        printf '%s\n' "$existing" >> "$tmp"
      fi
    done < "$ENV_FILE"
  fi

  if [[ "$found" == "0" ]]; then
    printf '%s\n' "$line" >> "$tmp"
  fi

  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE" 2>/dev/null || true
}

create_default_env() {
  mkdir -p "$LOCAL_DATA_DIR" "$LOCAL_DATA_DIR/runtime/cron/output" "$LOCAL_DATA_DIR/runtime/logs"
  mkdir -p "$(dirname "$ENV_FILE")"
  local old_umask
  old_umask="$(umask)"
  umask 077
  {
    echo "# Generated by ./run.sh. Keep this file private."
    echo "# Edit it directly or use /admin after the dashboard starts."
    write_env_value DASHBOARD_HOME "$LOCAL_DATA_DIR/runtime"
    write_env_value DASHBOARD_HOST "${DASHBOARD_HOST:-127.0.0.1}"
    write_env_value DASHBOARD_PORT "${DASHBOARD_PORT:-8787}"
    write_env_value PYTHON_BIN "$VENV_DIR/bin/python"
    echo
    write_env_value DASHBOARD_CONFIG "$LOCAL_DATA_DIR/runtime/config.yaml"
    write_env_value DASHBOARD_PUSH_HISTORY_DB "$LOCAL_DATA_DIR/runtime/push_history.db"
    write_env_value DASHBOARD_PORTFOLIO_STATE "$LOCAL_DATA_DIR/runtime/cron/output/niuniu_practice_portfolio.json"
    write_env_value DASHBOARD_TRADER_SCRIPT "$ROOT/app/entrypoints/niuniu_practice_trader.py"
    echo
    echo "# The dashboard stays public; settings and admin APIs always require authentication."
    echo "# Leave blank to use the bootstrap key at \$DASHBOARD_HOME/dashboard_admin_token.txt."
    write_env_value DASHBOARD_ADMIN_PASSWORD "${DASHBOARD_ADMIN_PASSWORD:-}"
  } > "$ENV_FILE"
  umask "$old_umask"
  chmod 600 "$ENV_FILE" 2>/dev/null || true
}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "== First run: creating private runtime files =="
  create_default_env
fi

if [[ "$PORT_ARG_SET" == "1" ]]; then
  save_env_value DASHBOARD_PORT "$PORT_ARG"
  echo "== Saved dashboard port to $ENV_FILE =="
fi

set -a
source "$ENV_FILE"
set +a

DASHBOARD_HOME="${DASHBOARD_HOME:-$LOCAL_DATA_DIR/runtime}"
DASHBOARD_HOST="${DASHBOARD_HOST:-127.0.0.1}"
DASHBOARD_PORT="${DASHBOARD_PORT:-8787}"
PYTHON_BIN="${PYTHON_BIN:-$VENV_DIR/bin/python}"

mkdir -p "$DASHBOARD_HOME/cron/output" "$DASHBOARD_HOME/logs"
mkdir -p "$LOCAL_DATA_DIR"

VENV_CREATED=0
if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "== Creating Python virtual environment =="
  if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is required but was not found in PATH." >&2
    exit 1
  fi
  mkdir -p "$(dirname "$VENV_DIR")"
  python3 -m venv "$VENV_DIR"
  PYTHON_BIN="$VENV_DIR/bin/python"
  VENV_CREATED=1
  save_env_value PYTHON_BIN "$PYTHON_BIN"
fi

if [[ "$INSTALL_DEPS" != "0" ]]; then
  REQ_HASH="$("$PYTHON_BIN" - "$ROOT/requirements.txt" <<'PY'
from hashlib import sha256
from pathlib import Path
import sys

print(sha256(Path(sys.argv[1]).read_bytes()).hexdigest())
PY
)"
  REQ_MARKER="$LOCAL_DATA_DIR/.requirements.sha256"
  INSTALLED_HASH=""
  [[ -f "$REQ_MARKER" ]] && INSTALLED_HASH="$(<"$REQ_MARKER")"
  if [[ "$VENV_CREATED" == "1" || "$REQ_HASH" != "$INSTALLED_HASH" ]]; then
    echo "== Installing Python dependencies =="
    "$PYTHON_BIN" -m pip install --upgrade pip
    "$PYTHON_BIN" -m pip install -r "$ROOT/requirements.txt"
    printf '%s\n' "$REQ_HASH" > "$REQ_MARKER"
  else
    echo "== Python dependencies are up to date =="
  fi
else
  echo "== Skipping dependency installation =="
fi

open_url() {
  if command -v open >/dev/null 2>&1; then
    open "$1"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$1"
  fi
}

open_dashboard_when_ready() {
  for _ in {1..80}; do
    if "$PYTHON_BIN" - "$DASHBOARD_HOST" "$DASHBOARD_PORT" <<'PY' >/dev/null 2>&1
import socket
import sys

host, port = sys.argv[1], int(sys.argv[2])
with socket.create_connection((host, port), timeout=0.25):
    pass
PY
    then
      open_url "$URL" >/dev/null 2>&1 || true
      return 0
    fi
    sleep 0.25
  done
  return 1
}

URL="http://$DASHBOARD_HOST:$DASHBOARD_PORT/"
export DASHBOARD_ENV_FILE="$ENV_FILE"
export DASHBOARD_HOME DASHBOARD_HOST DASHBOARD_PORT PYTHON_BIN

if [[ "$SERVICE_MODE" == "1" ]]; then
  echo "== Installing NiuOne long-running services =="
  "$ROOT/scripts/manage-long-running.sh" install
  echo "== NiuOne is running in service mode =="
  echo "  URL:        $URL"
  echo "  data:       $DASHBOARD_HOME"
  echo "  env:        $ENV_FILE"
  if [[ "$OPEN_BROWSER" != "0" ]]; then
    open_dashboard_when_ready || true
  fi
  exit 0
fi

echo "== Starting NiuOne Dashboard =="
echo "  URL:        $URL"
echo "  data:       $DASHBOARD_HOME"
echo "  env:        $ENV_FILE"
echo "  stop:       Ctrl+C"

if [[ "$OPEN_BROWSER" != "0" ]]; then
  open_dashboard_when_ready &
fi

exec "$ROOT/run-dashboard.sh"
